version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  product_service:
    build:
      context: product-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/marketplace
      - KEYCLOAK_ISSUER=http://localhost:8080/realms/marketplace
      - KEYCLOAK_JWKS_URL=http://keycloak:8080/realms/marketplace/protocol/openid-connect/certs
      - KEYCLOAK_AUDIENCE=account
    depends_on:
      - mongo

  frontend:
    build:
      context: frontend
    ports:
      - "5002:4173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=marketplace
      - VITE_KEYCLOAK_CLIENT=frontend
      - VITE_AUTH_URL=http://auth_service:3003
      - VITE_NOTIFY_URL=http://notification_service:4005
  bidding_service:
    build:
      context: bidding-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017/marketplace
      - GATEWAY_URL=http://gateway_service:3002/events
      - NOTIFY_URL=http://notification_service:4005/notify
      - KEYCLOAK_ISSUER=http://localhost:8080/realms/marketplace
      - KEYCLOAK_JWKS_URL=http://keycloak:8080/realms/marketplace/protocol/openid-connect/certs
      - KEYCLOAK_AUDIENCE=account
    depends_on:
      - mongo
      - gateway_service
      - notification_service
  gateway_service:
    build:
      context: gateway-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
  auth_service:
    build:
      context: auth-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=marketplace
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

volumes:
  mongo-data:
  notification-data:

