### Create product (valid)
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "iPhone",
  "price": 1099.99,
  "discountPercent": 10,
  "category": "electronics"
}

### Create product (valid)
POST http://localhost:3000/products
Content-Type: application/json

{
"title": "Laptop",
"price": 2999.99,
"discountPercent": 25,
"category": "electronics"
}

### Create product (valid)
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "PC",
  "price": 10000,
  "category": "electronics"
}

### Create product (invalid sample)
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "  ",
  "price": 100,
  "discountPercent": 0,
  "category": ""
}




### List products (default page=1,limit=10)
GET http://localhost:3000/products

### List products with pagination
GET http://localhost:3000/products?page=2&limit=2

### Get product by id (replace with real id)
GET http://localhost:3000/products/691188ff6a902afa3f69174d




### Update product by id (replace id)
PUT http://localhost:3000/products/691188ff6a902afa3f69174c
Content-Type: application/json

{
  "title": "iPhone Pro",
  "price": 1299.99,
  "discountPercent": 15,
  "category": "electronics"
}

### Update product by id (partial update)
PUT http://localhost:3000/products/691188ff6a902afa3f69174d
Content-Type: application/json

{
  "price": 999.99
}

### Delete product by id (replace id)
DELETE http://localhost:3000/products/691187bd6a902afa3f69174c
